"""WeChat multi-account manager using wechat_clawbot auth module."""

import asyncio
import json
import logging
import os
import shutil
from dataclasses import dataclass
from datetime import datetime

PROJECT_STATE_ROOT = os.path.join(os.getcwd(), "history", "openclaw-state")
PROJECT_WECHAT_STATE_DIR = os.path.join(PROJECT_STATE_ROOT, "openclaw-weixin")
LEGACY_OPENCLAW_STATE_DIR = os.path.expanduser("~/.openclaw")
LEGACY_WECHAT_STATE_DIR = os.path.join(LEGACY_OPENCLAW_STATE_DIR, "openclaw-weixin")


def _copy_missing_tree(src: str, dst: str) -> None:
    if not os.path.isdir(src):
        return
    os.makedirs(dst, exist_ok=True)
    for root, dirs, files in os.walk(src):
        rel = os.path.relpath(root, src)
        target_root = dst if rel == "." else os.path.join(dst, rel)
        os.makedirs(target_root, exist_ok=True)
        for dirname in dirs:
            os.makedirs(os.path.join(target_root, dirname), exist_ok=True)
        for fname in files:
            src_file = os.path.join(root, fname)
            dst_file = os.path.join(target_root, fname)
            if not os.path.exists(dst_file):
                shutil.copy2(src_file, dst_file)


_copy_missing_tree(LEGACY_WECHAT_STATE_DIR, PROJECT_WECHAT_STATE_DIR)
os.environ["OPENCLAW_STATE_DIR"] = PROJECT_STATE_ROOT

from wechat_clawbot.auth.accounts import (
    list_weixin_account_ids,
    load_weixin_account,
    save_weixin_account,
    clear_weixin_account,
    unregister_weixin_account_id,
    normalize_account_id,
)
from wechat_clawbot.auth.login_qr import (
    start_weixin_login_with_qr,
    wait_for_weixin_login,
)
from wechat_clawbot.claude_channel.credentials import AccountData, load_credentials

logger = logging.getLogger(__name__)

DEFAULT_BASE_URL = "https://ilinkai.weixin.qq.com"
WECHAT_STATE_DIR = PROJECT_WECHAT_STATE_DIR
WECHAT_OVERVIEW_PATH = os.path.join(os.getcwd(), "history", "WECHAT_ACCOUNTS_OVERVIEW.md")


@dataclass
class AccountInfo:
    account_id: str
    user_id: str | None
    saved_at: str | None
    base_url: str | None
    display_name: str | None = None
    skill: str | None = None  # bound skill name


class WeChatAccountManager:
    def __init__(self):
        self._loop: asyncio.AbstractEventLoop | None = None
        self._migrate_old_account()
        self.write_overview()

    def _ensure_loop(self):
        if self._loop is None or self._loop.is_closed():
            self._loop = asyncio.new_event_loop()
        return self._loop

    def _run_async(self, coro):
        loop = self._ensure_loop()
        return loop.run_until_complete(coro)

    def _migrate_old_account(self):
        """Migrate account from old single-account location if exists."""
        existing = list_weixin_account_ids()
        if existing:
            return  # Already has accounts in new system

        old_creds = load_credentials()
        if old_creds and old_creds.account_id:
            logger.info(f"Migrating old account: {old_creds.account_id}")
            save_weixin_account(
                account_id=old_creds.account_id,
                token=old_creds.token,
                base_url=old_creds.base_url,
                user_id=old_creds.user_id,
            )

    def list_accounts(self) -> list[AccountInfo]:
        """List all saved WeChat accounts."""
        account_ids = self._list_known_account_ids()
        bindings = self._load_skill_bindings()
        aliases = self._load_account_aliases()
        accounts = []
        for aid in account_ids:
            data = load_weixin_account(aid)
            skill = bindings.get(aid)
            alias = aliases.get(aid, {})
            display_name = alias.get("name") if isinstance(alias, dict) else None
            if data:
                accounts.append(AccountInfo(
                    account_id=aid,
                    user_id=data.user_id,
                    saved_at=data.saved_at,
                    base_url=data.base_url,
                    display_name=display_name,
                    skill=skill,
                ))
            else:
                accounts.append(AccountInfo(
                    account_id=aid,
                    user_id=None,
                    saved_at=None,
                    base_url=None,
                    display_name=display_name,
                    skill=skill,
                ))
        return accounts

    def write_overview(self) -> None:
        """Write a human-readable overview of local WeChat account state."""
        try:
            accounts = self.list_accounts()
            aliases = self._load_account_aliases()
            bindings = self._load_skill_bindings()
            last_account_id = self.get_last_account_id()
            lines = [
                "# WeChat Account Overview",
                "",
                "This file is generated by the agent. It summarizes local WeChat bot account state without printing tokens.",
                "",
                f"- State root: `{PROJECT_STATE_ROOT}`",
                f"- WeChat state: `{WECHAT_STATE_DIR}`",
                f"- Last account: `{last_account_id or '-'}`",
                "",
                "## Accounts",
                "",
            ]
            if not accounts:
                lines.append("No saved WeChat bot accounts.")
            for index, account in enumerate(accounts, 1):
                alias = aliases.get(account.account_id, {}) if isinstance(aliases.get(account.account_id), dict) else {}
                history_key = alias.get("history_key") or "-"
                credential_file = os.path.join(WECHAT_STATE_DIR, "accounts", f"{account.account_id}.json")
                lines.extend([
                    f"### {index}. {account.display_name or account.account_id}",
                    "",
                    f"- account_id: `{account.account_id}`",
                    f"- active: `{'yes' if account.account_id == last_account_id else 'no'}`",
                    f"- skill: `{bindings.get(account.account_id) or '-'}`",
                    f"- history_key: `{history_key}`",
                    f"- saved_at: `{account.saved_at or '-'}`",
                    f"- credential_file: `{credential_file}`",
                    "",
                ])
            os.makedirs(os.path.dirname(WECHAT_OVERVIEW_PATH), exist_ok=True)
            with open(WECHAT_OVERVIEW_PATH, "w", encoding="utf-8") as f:
                f.write("\n".join(lines).rstrip() + "\n")
        except Exception as e:
            logger.warning(f"Failed to write WeChat account overview: {e}")

    def get_account(self, account_id: str) -> AccountData | None:
        """Load account credentials as AccountData for WeChatClient."""
        data = load_weixin_account(account_id)
        if not data or not data.token:
            return None
        return AccountData(
            token=data.token,
            base_url=data.base_url or DEFAULT_BASE_URL,
            account_id=account_id,
            user_id=data.user_id,
            saved_at=data.saved_at,
        )

    def get_default_account(self) -> tuple[AccountData | None, str | None]:
        """Load the last selected account, falling back to the first saved account."""
        account_id = self.get_last_account_id()
        if account_id:
            account = self.get_account(account_id)
            if account:
                return account, account_id

        accounts = self.list_accounts()
        if not accounts:
            return None, None

        account_id = accounts[0].account_id
        account = self.get_account(account_id)
        if account:
            self.set_last_account_id(account_id)
            return account, account_id
        return None, None

    def _list_known_account_ids(self) -> list[str]:
        """List accounts from both wechat_clawbot index and account files."""
        seen: set[str] = set()
        ordered: list[str] = []

        def add(account_id: str | None) -> None:
            if not account_id or account_id in seen:
                return
            seen.add(account_id)
            ordered.append(account_id)

        add(self.get_last_account_id())

        for account_id in list_weixin_account_ids():
            add(account_id)

        accounts_dir = os.path.join(WECHAT_STATE_DIR, "accounts")
        if os.path.isdir(accounts_dir):
            for fname in sorted(os.listdir(accounts_dir)):
                if not fname.endswith(".json") or fname.endswith(".context-tokens.json"):
                    continue
                add(os.path.splitext(fname)[0])

        for account_id in self._load_account_aliases().keys():
            add(account_id)

        return ordered

    def qr_login(self) -> AccountData | None:
        """Run QR code login flow. Returns AccountData on success, None on failure."""
        print("\n正在获取微信扫码登录二维码...")

        result = self._run_async(
            start_weixin_login_with_qr(api_base_url=DEFAULT_BASE_URL)
        )

        if not result.qrcode_url:
            print(f"获取二维码失败: {result.message}")
            return None

        print(f"\n请用微信扫描以下链接打开的二维码：")
        print(f"  {result.qrcode_url}")
        print(f"\n或在浏览器中打开此链接扫码。")
        print(f"等待扫码中", end="", flush=True)

        try:
            import webbrowser
            webbrowser.open(result.qrcode_url)
            print(" (已在浏览器中打开)")
        except Exception:
            print()

        wait_result = self._run_async(
            wait_for_weixin_login(
                session_key=result.session_key,
                api_base_url=DEFAULT_BASE_URL,
                verbose=True,
            )
        )

        print()  # newline after dots

        if not wait_result.connected:
            print(f"登录失败: {wait_result.message}")
            return None

        # Save the account
        account_id = wait_result.account_id
        save_weixin_account(
            account_id=account_id,
            token=wait_result.bot_token,
            base_url=wait_result.base_url,
            user_id=wait_result.user_id,
        )

        print(f"登录成功! 账号: {account_id}")
        self.set_last_account_id(account_id)
        self.write_overview()

        return AccountData(
            token=wait_result.bot_token,
            base_url=wait_result.base_url or DEFAULT_BASE_URL,
            account_id=account_id,
            user_id=wait_result.user_id,
        )

    def remove_account(self, account_id: str) -> bool:
        """Remove an account. Returns True if successful."""
        try:
            clear_weixin_account(account_id)
            unregister_weixin_account_id(account_id)
            aliases = self._load_account_aliases()
            aliases.pop(account_id, None)
            self._save_account_aliases(aliases)
            bindings = self._load_skill_bindings()
            bindings.pop(account_id, None)
            self._save_skill_bindings(bindings)
            state = self._load_state()
            if state.get("last_account_id") == account_id:
                state.pop("last_account_id", None)
                self._save_state(state)
            self.write_overview()
            return True
        except Exception as e:
            logger.warning(f"Failed to remove account {account_id}: {e}")
            return False

    def _bindings_path(self) -> str:
        return os.path.join(WECHAT_STATE_DIR, "skill-bindings.json")

    def _aliases_path(self) -> str:
        return os.path.join(WECHAT_STATE_DIR, "account-aliases.json")

    def _state_path(self) -> str:
        return os.path.join(WECHAT_STATE_DIR, "agent-state.json")

    def _load_state(self) -> dict:
        path = self._state_path()
        if not os.path.exists(path):
            return {}
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            return data if isinstance(data, dict) else {}
        except Exception:
            return {}

    def _save_state(self, state: dict) -> None:
        path = self._state_path()
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(state, f, indent=2, ensure_ascii=False)

    def get_last_account_id(self) -> str | None:
        """Return the account id selected in the last run."""
        data = self._load_state()
        account_id = data.get("last_account_id")
        return account_id if isinstance(account_id, str) and account_id else None

    def set_last_account_id(self, account_id: str):
        """Persist the account id to use by default next time."""
        state = self._load_state()
        state["last_account_id"] = account_id
        self._save_state(state)
        self.write_overview()

    def _load_account_aliases(self) -> dict[str, dict]:
        path = self._aliases_path()
        if not os.path.exists(path):
            return {}
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            return data if isinstance(data, dict) else {}
        except Exception:
            return {}

    def _save_account_aliases(self, aliases: dict[str, dict]) -> None:
        path = self._aliases_path()
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(aliases, f, indent=2, ensure_ascii=False)

    def set_account_display_name(self, account_id: str, name: str | None) -> None:
        """Persist a friendly display name for a WeChat bot account."""
        display_name = (name or "").strip() or account_id
        aliases = self._load_account_aliases()
        existing = aliases.get(account_id, {}) if isinstance(aliases.get(account_id), dict) else {}
        aliases[account_id] = {
            **existing,
            "name": display_name,
            "updated_at": datetime.now().isoformat(),
        }
        self._save_account_aliases(aliases)
        self.write_overview()

    def get_account_display_name(self, account_id: str | None) -> str | None:
        if not account_id:
            return None
        aliases = self._load_account_aliases()
        alias = aliases.get(account_id, {})
        if isinstance(alias, dict):
            name = alias.get("name")
            if isinstance(name, str) and name.strip():
                return name.strip()
        return account_id

    def get_account_history_key(self, account_id: str | None) -> str | None:
        if not account_id:
            return None
        alias = self._load_account_aliases().get(account_id, {})
        if isinstance(alias, dict):
            history_key = alias.get("history_key")
            if isinstance(history_key, str) and history_key.strip():
                return history_key.strip()
        return None

    def set_account_history_key(self, account_id: str, history_key: str) -> None:
        aliases = self._load_account_aliases()
        existing = aliases.get(account_id, {}) if isinstance(aliases.get(account_id), dict) else {}
        aliases[account_id] = {
            **existing,
            "history_key": history_key,
            "updated_at": datetime.now().isoformat(),
        }
        self._save_account_aliases(aliases)
        self.write_overview()

    def resolve_account_selector(self, selector: str) -> AccountInfo | None:
        """Resolve a list index, account id, or display name to an account."""
        selector = selector.strip()
        if not selector:
            return None
        accounts = self.list_accounts()
        if selector.isdigit():
            index = int(selector)
            if 1 <= index <= len(accounts):
                return accounts[index - 1]
        normalized = selector.lower()
        for account in accounts:
            if account.account_id.lower() == normalized:
                return account
        for account in accounts:
            if account.display_name and account.display_name.lower() == normalized:
                return account
        return None

    def _load_skill_bindings(self) -> dict[str, str]:
        """Load skill bindings: {account_id: skill_name}."""
        path = self._bindings_path()
        if not os.path.exists(path):
            return {}
        try:
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            return {}

    def _save_skill_bindings(self, bindings: dict[str, str]):
        """Save skill bindings."""
        path = self._bindings_path()
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(bindings, f, indent=2, ensure_ascii=False)

    def bind_skill(self, account_id: str, skill_name: str):
        """Bind a skill to an account."""
        bindings = self._load_skill_bindings()
        bindings[account_id] = skill_name
        self._save_skill_bindings(bindings)
        logger.info(f"Bound skill '{skill_name}' to account '{account_id}'")
        self.write_overview()

    def unbind_skill(self, account_id: str):
        """Remove skill binding from an account."""
        bindings = self._load_skill_bindings()
        bindings.pop(account_id, None)
        self._save_skill_bindings(bindings)
        self.write_overview()

    def get_bound_skill(self, account_id: str) -> str | None:
        """Get the skill bound to an account."""
        bindings = self._load_skill_bindings()
        return bindings.get(account_id)
